Feature: Scenario 3

  @user1 @web
  Scenario Outline: Admin creates a new tag and list the tags
    Given Admin starts app
    When Bot sets 3 scenario
    And Admin navigates to "/tags" page
    And I wait for 1 seconds
    And Admin clicks to new Tag
    And I wait for 1 seconds
    And Admin creates new Tag with name "<tagName>" and description "<tagDescription>"
    And I wait for 1 seconds
    And Admin navigates to "/tags" page and expected total <tagTotal>
    And I wait for 1 seconds
    Then Admin sees <tagTotal> tags

    Examples:
      | tagTotal | tagName                                                                                                                                                                                          | tagDescription                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
      | 0        |                                                                                                                                                                                                  | Nulla suscipit ligula in lacus.\n\nCurabitur at ipsum ac tellus semper interdum.                                                                                                                                                                                                                                                                                                                                                                                                                                      |
      | 0        | 192 caracteres convallis morbi odio odio elementum eu intdum eu tincidunt in leo maecenas pulvinar lobortis est phasellus sit amet erat convallis morbi odio odio elementum eu interdum eu tincj |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
      | 1        | 191 caracteres convallis morbi odio odio elementum eu intdum eu tincidunt in leo maecenas pulvinar lobortis est phasellus sit amet erat convallis morbi odio odio elementum eu interdum eu tinc  | Nulla suscipit ligula in lacus.\n\nCurabitur at ipsum ac tellus semper interdum.                                                                                                                                                                                                                                                                                                                                                                                                                                      |
      | 1        | 190 caracteres convallis morbi odio odio elementum eu intdum eu tincidunt in leo maecenas pulvinar lobortis est phasellus sit amet erat convallis morbi odio odio elementum eu interdum eu tin   | Curabitur convallis.\n\nDuis consequat dui nec nisi volutpat eleifend.                                                                                                                                                                                                                                                                                                                                                                                                                                                |
      | 1        | 1                                                                                                                                                                                                | Integer a nibh.\n\nIn quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.                                                                                                                                                                                                                                                                                                                                                                                                        |
      | 1        | 191 caracteres convallis morbi odio odio elementum eu intdum eu tincidunt in leo maecenas pulvinar lobortis est phasellus sit amet erat convallis morbi odio odio elementum eu interdum eu tinc  | 500 caracteres Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nistory inn  |
      | 0        | descUpper                                                                                                                                                                                        | 501 caracteres Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nistory item |
      | 1        | descLower                                                                                                                                                                                        | 499 caracteres Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nistory in   |
      | 0        | 192 caracteres convallis morbi odio odio elementum eu intdum eu tincidunt in leo maecenas pulvinar lobortis est phasellus sit amet erat convallis morbi odio odio elementum eu interdum eu tinck | 501 caracteres Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nistory item |
      | 1        | a                                                                                                                                                                                                | b                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
